### ISSUE TITLE
Export To PDF

### ISSUE THREAD

**Issue by Paaaaaaul** [iamtheprogram/AcademicCalendarLU#25]
Essentially, if the menu button "Export to PDF" is clicked it should open the print dialog window and the user should select the adobe printer to pdf which then prints a table accordingly to the design of the client with all events and dates of events ordered by date

**Comment by iamtheprogram** [comment]
Closing this.
Solution: Make sure to set Accessible Text field.

**Comment by iamtheprogram** [comment]
Nevermind I didn't read the whole thing .......

**Comment by iamtheprogram** [comment]
Thanks paul
